### ISSUE TITLE
Extending to the atompub protocol and http api

### ISSUE THREAD

**Issue by CrowdHailer** [exponentially/extreme#15]
I think Extreme just uses the TCP API. Would it be a separate project or an extension to this project to extend it to using the http api

> In general our recommendation would be to use AtomPub as your primary protocol unless you have low subscriber SLAs or need higher throughput on reads and writes than Atom can offer. This is largely due to the open nature and ease of use of the Atom protocol. Very often in integration scenarios these are more important than raw performance.

**Comment by burmajam** [comment]
Hi Peter,

Extreme only uses TCP for now. I'd like to see AtomPub based solution as well but I'm not sure if it should be part of Extreme itself, since results would be the same. However we are opened for discussion on this subject

**Comment by CrowdHailer** [comment]
I have time to start writing some elixir and perhaps tackling something like a library for Atom pub would be a great project. Would you be interested in giving advice now and again

**Comment by burmajam** [comment]
Hey @CrowdHailer,

Sorry, this message somehow went out of my radar. Of course I'm willing to help if I can (if its not too late now :)

**Comment by CrowdHailer** [comment]
It's not too late, I had to put the project on hold. Although it looks like I might be getting some resources to explore this further in january so fingers crossed that I'll be doing something interesting then.

**Comment by burmajam** [comment]
Good, so fingers crossed then and please don't hesitate to reach me if I can be of any help
