### ISSUE TITLE
Notify subscriber when 'caught up' with buffered messages

### ISSUE THREAD

**Issue by yammine** [exponentially/extreme#16]
Hey there,

First of all: thank you very much for this library, I'm grateful for all of the work you've done so far.

I was making a read model in my application and was thinking that it would be great if the subscription process could notify my subscribing process that it has finished sending all of the buffered messages. 

The reason is that I don't really want my reader to respond with what presumably stale data when it's being spun up as the result of a query.

Does this even make sense? Is there some existing way to do this that I'm oblivious to?

The change would look something like this:

`subscription.ex`

``` elixir
def handle_cast(:push_buffered_messages, state) do
  state.buffered_messages |> Enum.each(fn(e)-> send(state.subscriber, {:on_event, e}) end)
  send state.subscriber, :caught_up # <-- this
  {:noreply, %{state|status: :subscribed, buffered_messages: []}}
end
```

Thanks for your time 😄

**Comment by burmajam** [comment]
Hi Chris,

Thank you for kind words. Your appreciation means alot to us :) We are trying to make this library as simple as possible but also to have everything one needs for successful use of EventStore which is really great.

That being said, I think that your request makes sense and I'll do my best to make and test it asap. I'll let you know once I push changes to master so you can try it first before pushing to hex, if that's ok with you?

Thanks,

Milan

**Comment by burmajam** [comment]
Hey Chris,

I've added requested feature with test and documentation. It is on master now. If you've been using Extreme.Listener, there's optional callback there as well (see in documentation and test). Please try and if that works for you I'll push it to hex.

Thanks,

**Comment by yammine** [comment]
Thanks alot @burmajam :) I'll test it shortly

**Comment by yammine** [comment]
Excellent 👍  exactly what I needed 😄  

Thank you again

**Comment by burmajam** [comment]
Great! Glad to hear that it works for you. You can find it now on hex as well.

Thanks for idea :)
