### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme#21]
I'm trying to write to a local EventStore instance on my windows machine, and it seems like it can't even handle 100 items/second. It takes around 100ms for each write.

Am I doing something wrong? 

My eventstore is started as follows:

```EventStore.ClusterNode.exe --run-projections=all```

and my extreme code looks as follows:

```
def publish_to_es(stream_id, event_id, event_type, event_data) do
		server = Evstore.EventStore

		event = Extreme.Messages.NewEvent.new(
			event_id: event_id,
			event_type: event_type, # event_type,
			data_content_type: 0, 
			metadata_content_type: 0, 
			data: event_data,
			meta: "")

		write_events = Extreme.Messages.WriteEvents.new(
			event_stream_id: stream_id, events: [event], 
			expected_version: -2, require_master: false)

		{:ok, _response} = Extreme.execute server, write_events
	end
```

**Comment by burmajam** [comment]
Hi drozzy,

Thank you for writing. Unfortunately, we didn't try on windows machine any elixir code, hence extreme is not tested on it as well. As for code, it looks ok to me. We didn't benchmark extreme but we use it in production for more than a year on heavy load, it works really fast and we didn't face any problems yet. We have tried it on os x, ubuntu and centos so far without performance or any other issues.

Did you benchmark Extreme.execute function? I can benchmark on my osx with 100 events if you want and can send you outcome?

**Comment by burmajam** [comment]
Just measured it. It takes ~ 1.5ms per event on 1_000 events, so execution time for writing all 1_000 events was 1_454_274 µsec

**Comment by burmajam** [comment]
On Travis it works even twice faster https://travis-ci.org/exponentially/extreme#L541

**Comment by drozzy** [comment]
This is my fault entirely!

I was writing events sequentially (hence the `[event]` in the code). Turns out if you send 100 at a time it works just as fast. My bad. I just never worked with fast throughput before.

Is there a way to batch read the events by the way?

**Comment by burmajam** [comment]
Actually, sequential write should be much faster. If you take a look at test @ https://github.com/exponentially/extreme/blob/master/test/extreme_test.exs#L449 you'll see that I'm writing 500 times 2 events and execution time I mentioned before is for such action.

By batch read you mean reading all events in specified stream? If so, take a look @ https://github.com/exponentially/extreme/blob/master/test/extreme_test.exs#L66
