### ISSUE TITLE
Restart Extreme connection after  TCP failure

### ISSUE THREAD

**Issue by henry-hz** [exponentially/extreme#24]
When I shutdown Eventstore, all my application shuts down, even that the supervision are setup to permanent
@mindreframer I renamed the app to workflow ;)

Pls, if you can review.

```
git clone https://github.com/work-capital/workflow.git
iex -S mix
:observer.start
```

**Comment by burmajam** [comment]
You can specify in extreme config reconnect_delay and max_attempts. These are defaults:

    reconnect_delay: 1_000,
    max_attempts: :infinity

Extreme won't crash if connection is lost, I guess something else crashes that depends on it. Try to start extreme in supervision tree with eventstore up, shutdown ES and watch in your app log how extreme tries to reconnect.

However, I found that Extreme.Listener and Extreme.FanoutListener will crash if connection is lost. I have to figure out what is the best approach for that

**Comment by henry-hz** [comment]
Thank you very much!
