### ISSUE TITLE
Implement backpresue, acking received events

### ISSUE THREAD

**Issue by henry-hz** [exponentially/extreme#27]
There is an important PR in commanded, by [sharksdontfly](https://github.com/slashdotdash/commanded/pull/47) that implements extreme support in commanded framework. Let me suggest to add into extreme a feature that apparently exists in eventstore-postgres.

from: https://github.com/slashdotdash/eventstore#ack-received-events
"Ack received events Receipt of each event by the subscriber must be acknowledged. This allows the subscription to resume on failure without missing an event.

The subscriber receives an {:events, events, subscription} tuple containing the published events and the subscription to send the ack to. This is achieved by sending an {:ack, last_seen_event_id} tuple to the subscription process. A subscriber can confirm receipt of each event in a batch by sending multiple acks, one per event. Or just confirm receipt of the last event in the batch.

A subscriber will not receive further published events until it has confirmed receipt of all received events. This provides back pressure to the subscription to prevent the subscriber from being overwhelmed with messages if it cannot keep up. The subscription will buffer events until the subscriber is ready to receive, or an overflow occurs. At which point it will move into a catch-up mode and query events and replay them from storage until caught up."

**Comment by burmajam** [comment]
Extreme.Listener does exactly what are you looking for I think. Please take a look at readme and listener_test and let me know if that's the feature you need.

**Comment by henry-hz** [comment]
@burmajam we thought about your suggestion. @slashdotdash implementend for extreme using the same approach he used on eventstore(postrge)  https://github.com/slashdotdash/commanded/pull/47 
thanks for the follow up
