### ISSUE TITLE
Elixir 1.4?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme#28]
Does this work with Elixir 1.4?

**Comment by burmajam** [comment]
Tests are passing but there are a lot of warning messages, since I prefer to call functions without parenthesis

**Comment by henry-hz** [comment]
I tested here, took me 40 seconds to write 1000 messages, my machine is a i7, 8 processors, 16gig ram, debian...   I am running eventstore on docker for development.

**Comment by burmajam** [comment]
Strange, I've noticed that it looks slower but on my MBP i7, 4CPU, 16gig it took ~3 seconds to write 500 times 2 events, which is roughly twice as slow as it is with 1.3.4. @henry-hz, is that result from extreme_test? There's one that measures this

**Comment by henry-hz** [comment]
@burmajam yes, in my machine using docker. I am building eventstore (only ubuntu...) to try. our cto made 2.3 seconds (first time JIT) with native mac eventstore installed. Second time 1000 events/ 1.2 seconds

![image](https://cloud.githubusercontent.com/assets/1010008/21891277/8ea35ed8-d8da-11e6-9ffd-ed69968a6be4.png)

Oho, docker in mac, 35 seconds. So we found the bottleneck... docker...

**Comment by burmajam** [comment]
Wow, you don't have the same issues with docker and elixir 1.3.4?

**Comment by henry-hz** [comment]
I remember I also had seen, not sure. Seems docker is dynamically creating disk space... eventstore is optimized for ssd, access direct to the disk. in [dockerhub](https://hub.docker.com/r/eventstore/eventstore/) they say:  "Note: This container is for development purposes only" . I am curious to know, how long it would take in your machine using docker. 
```
docker run -it -p 2113:2113 -p 1113:1113 eventstore/eventstore
```

**Comment by drozzy** [comment]
Verified that it works with Elixir 1.4, only with some warning messages. Feel free to close.

**Comment by henry-hz** [comment]
sure, not related to 1.4.  I just tested in 1.4 because I saw it in this issue... and got that test. Interesting that in travis it's passing... also docker

**Comment by burmajam** [comment]
Thanks for feedback guys. I'll try to remove extreme warnings in near future for elixir 1.4.
