### ISSUE TITLE
Retrieve a list of all streams

### ISSUE THREAD

**Issue by lanarchyste** [exponentially/extreme#29]
Hello,

I try to get the list of all the streams, I read from the documentation that this is possible but I can not implement it with extreme.

For the moment, I test the following codes that returns every time an error:
`{:ok, response} = Extreme.execute server, ExMsg.ReadAllEvents.new(..)`

> (FunctionClauseError) no function clause matching in Extreme.MessageResolver.encode_cmd/1

and

`{:ok, response} = Extreme.execute server, :read_all_events_forward`

> (UndefinedFunctionError) function :read_all_events_forward.__struct__/0 is undefined (module :read_all_events_forward is not available)

Does the code currently implement a way to get a list of all the streams? If so, can you provide me with a sample code?

I can already read all events for a stream.

Thank you.

Best regards
Julien.

**Comment by burmajam** [comment]
Hi Julien,

This is EventStore thing. You can start $streams builtin projection in ES and then read from "$streams" stream using Extreme or browser (http://localhost:2114/web/index.html#/streams/$streams) :)

**Comment by lanarchyste** [comment]
Hi,

Currently I have no problem reading all the events of a stream or subscribing to a stream.

What I want is to get all the streams available since the code using Extreme (just the name of the streams would be enough), and I would like to know if it's possible and by which way.

**Comment by burmajam** [comment]
Yeah, I got that. One way to get that is to start that $streams projection. Than you read from "$streams" stream in extreme and you'll get first event of each stream. From that event you can have what stream it belongs to. HOWEVER, if you have soft deleted streams and then wrote to them again they won't appear in that "$streams" stream. Take a look Gregs comments @ https://groups.google.com/forum/#!topic/event-store/EQk1YlEbHIw

Maybe there's a better way to achieve what you want, but I don't know what is your intention.

**Comment by lanarchyste** [comment]
Hi,

Thank you very much for these explanations !

By using the $streams projection that I did not know, I was able to do what I wanted :)
