### ISSUE TITLE
subscribe to deleted stream error

### ISSUE THREAD

**Issue by revati** [exponentially/extreme#3]
When subscribing with `Extreme.read_and_stay_subscribed` to non existing stream stream, it seems it has some internal bug?

```
[error] GenServer #PID<0.316.0> terminating
** (FunctionClauseError) no function clause matching in Extreme.Subscription.process_response/2
    (extreme) lib/subscription.ex:65: Extreme.Subscription.process_response({:error, :StreamDeleted, %Extreme.Messages.ReadStreamEventsCompleted{error: "", events: [], is_end_of_stream: true, last_commit_position: 45902490, last_event_number: 2147483647, next_event_number: -1, result: :StreamDeleted}}, %{buffered_messages: [], connection: #PID<0.296.0>, read_params: %{from_event_number: 0, per_page: 4096, require_master: false, resolve_link_tos: true, stream: "Domain.Acl.AclAggregate"}, read_until: 2147483648, status: :reading_events, subscriber: Domain.Acl.AclAggregate})
    (extreme) lib/subscription.ex:48: Extreme.Subscription.handle_cast/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :read_events}
State: %{buffered_messages: [], connection: #PID<0.296.0>, read_params: %{from_event_number: 0, per_page: 4096, require_master: false, resolve_link_tos: true, stream: "Domain.Acl.AclAggregate"}, read_until: 2147483648, status: :reading_events, subscriber: Domain.Acl.AclAggregate}
```

**Comment by mjaric** [comment]
From error, I could say that you actually tried to subscribe to deleted stream. Could you please confirm? Otherwise I cannot reproduce this error, so I will need more details about case.

**Comment by revati** [comment]
Yes i deleted that stream.
I don't know how to mock eventstore, for now i just run tests and before running them i delete all streams.

**Comment by mjaric** [comment]
There are 2 ways. It depends on in which direction domain events need to go. In case you want to store events, then you simple need mock process (instead of extreme pid). This mock eventstore process should receive all events with callback `handle_call({:execute, events}, _from, _state)` or even better, simply in your test case file use `self` and `assert_receive {:execute, _events }`. You can also check events after that assertion. Don't use Extreme.execute since then you have to fire up all bunch of infrastructure things. 

Second direction is when you want to check how events are applied to your aggregate/process state. In this case simple cast/call that pid with list of hardcoded events  :) Extreme is using :on_event atom so you have to handle this in your callback anyway.

This way you don't depend on extreme module in your test cases, and you don't have to have EventStore running.

**Comment by revati** [comment]
I just started implementing end to end tests for api. Api call and assert response. So in regular mysql i still would just have db which i create before each test and drop after test.

As i understand eventstore does not require explicit stream creation. I just start to put events in a stream and its good. so i only need to delete stream after tests have been executed.

But when i run tests next time error is thrown :(

**Comment by mjaric** [comment]
in such case, I suggest that you start event store with "in memory" database, and restart it each time you run tests again. Or, use GUID if possible in stream name. I'm not sure what dictates unique names in your case. EventStore is designed to return `StreamDeleted` status if it is hard deleted or `NoStream` if it is soft deleted. 

It is worth to mention, it is possible to make subscription to non existing stream in case when it never existed in database, so whenever it is created, subscription will start receiving events. 

Anyhow, there is issue in extreme, the info should be returned if stream is hard/soft deleted, during already established subscription or any new subscription to deleted stream. I see that internal error will shutdown subscription process and no other process would be informed that something happen.

Thanks, we will fix this issue

**Comment by revati** [comment]
Thanks, for your response, will try with in memory database, it will do the trick :)

Great library :)

**Comment by burmajam** [comment]
There is an issue when calling read_and_stay_subscribed on non-existing stream. We'll fix it soon

**Comment by revati** [comment]
how is it going?
when approximately could this bug be fixed?

**Comment by burmajam** [comment]
Hi Roberts,

Can you please try branch https://github.com/exponentially/extreme/tree/deleted_stream_subscription_fix?files=1. That should fix problem. We should test it more before pushing version to hex

Milan Burmaja

**Comment by revati** [comment]
Its odd, i remember, how i already answered to this few days ago :|

I tried that branch and it works

```
// When compiling
lib/message_resolver.ex:8: warning: clauses for the same def should be grouped together, def decode_cmd/1 was previously defined (lib/message_resolver.ex:4)
lib/message_resolver.ex:27: warning: clauses for the same def should be grouped together, def encode_cmd/1 was previously defined (lib/message_resolver.ex:5)
lib/message_resolver.ex:30: warning: clauses for the same def should be grouped together, def decode_cmd/1 was previously defined (lib/message_resolver.ex:4)
lib/message_resolver.ex:32: warning: clauses for the same def should be grouped together, def encode_cmd/1 was previously defined (lib/message_resolver.ex:5)
lib/message_resolver.ex:33: warning: clauses for the same def should be grouped together, def decode_cmd/1 was previously defined (lib/message_resolver.ex:4)
lib/message_resolver.ex:34: warning: clauses for the same def should be grouped together, def encode_cmd/1 was previously defined (lib/message_resolver.ex:5)
lib/message_resolver.ex:35: warning: clauses for the same def should be grouped together, def decode_cmd/1 was previously defined (lib/message_resolver.ex:4)
lib/message_resolver.ex:36: warning: clauses for the same def should be grouped together, def encode_cmd/1 was previously defined (lib/message_resolver.ex:5)
lib/message_resolver.ex:37: warning: clauses for the same def should be grouped together, def decode_cmd/1 was previously defined (lib/message_resolver.ex:4)
lib/message_resolver.ex:39: warning: clauses for the same def should be grouped together, def encode_cmd/1 was previously defined (lib/message_resolver.ex:5)
lib/message_resolver.ex:40: warning: clauses for the same def should be grouped together, def decode_cmd/1 was previously defined (lib/message_resolver.ex:4)
lib/message_resolver.ex:42: warning: clauses for the same def should be grouped together, def encode_cmd/1 was previously defined (lib/message_resolver.ex:5)
lib/message_resolver.ex:43: warning: clauses for the same def should be grouped together, def decode_cmd/1 was previously defined (lib/message_resolver.ex:4)
lib/message_resolver.ex:46: warning: clauses for the same def should be grouped together, def encode_cmd/1 was previously defined (lib/message_resolver.ex:5)
lib/message_resolver.ex:47: warning: clauses for the same def should be grouped together, def decode_cmd/1 was previously defined (lib/message_resolver.ex:4)
lib/message_resolver.ex:49: warning: clauses for the same def should be grouped together, def encode_cmd/1 was previously defined (lib/message_resolver.ex:5)
lib/message_resolver.ex:57: warning: clauses for the same def should be grouped together, def decode_cmd/1 was previously defined (lib/message_resolver.ex:4)
lib/message_resolver.ex:59: warning: clauses for the same def should be grouped together, def encode_cmd/1 was previously defined (lib/message_resolver.ex:5)
==> extreme
Compiled lib/cluster_connection.ex
lib/message_resolver.ex:82: warning: clauses for the same def should be grouped together, def decode_cmd/1 was previously defined (lib/message_resolver.ex:4)
```

**Comment by burmajam** [comment]
Thanks Roberts. Besides those annoying warning messages, does it behave as expected for you?

**Comment by revati** [comment]
Yes, it works like it should (like i need)

When subscribing to stream that does not exist, it shows `[warn] Stream doesn't exist yet`, but still subscribes to it.

**Comment by burmajam** [comment]
Great. We'll do some more tests and will publish fixed version to hex soonish. Thanks again for reporting
