### ISSUE TITLE
Unsubscribe?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme#30]
How can I unsubscribe from event store?

E.g. I'm replaying an aggregate with `Extreme.read_and_stay_subscribed`, but when I am `caught_up` - I don't need to receive the events anymore (since I apply them locally to my aggregate).

Thank you.

**Comment by mjaric** [comment]
i think you want to use read_events_forward it will send you eg 4000 events, then read in metadata what is last event number and then read 4k more until counter reaches the end of stream

**Comment by drozzy** [comment]
Thanks. How will I know when I reach the end of stream? The reason I used "read_and_stay_subscribed" is because it has a nice "caught_up" message.

**Comment by drozzy** [comment]
Do you mean `read_events`? I can't seem to find `read_events_forward` in the code...

**Comment by mjaric** [comment]
https://github.com/exponentially/extreme/blob/master/include/event_store.proto#L173

is_end_of_stream is what you need

**Comment by mjaric** [comment]
this struct is returned each time you do read_events_forward. just increment from parameter until flag above is true

**Comment by drozzy** [comment]
Nice, is there an example of usage somewhere?

Still can't find `read_events_forward` in the code :-(

**Comment by mjaric** [comment]
there is few examples in tests like this one. https://github.com/exponentially/extreme/blob/master/test/extreme_test.exs#L72 

read_events is helper function in tests o check it to see how it builds request

**Comment by drozzy** [comment]
Thanks!

For future reference, this is how it looks in Erlang:

```erlang
-spec read_events(StreamId::binary(), FromEventNumber::non_neg_integer(), MaxCount::non_neg_integer()) -> {ok, EventStruct::#    {}} | {error, Reason::term()}.
read_events(StreamId, FromEventNumber, MaxCount) ->
    ReadEvents = 'Elixir.Extreme.Messages.ReadStreamEvents':new([
         {event_stream_id, StreamId},
         {from_event_number, FromEventNumber}, 
         {resolve_link_tos, true},   
         {max_count, MaxCount}, 
         {require_master, false}]),  
    'Elixir.Extreme':execute(?ES_SERVER, ReadEvents).
```
