### ISSUE TITLE
Set maxCount on the stream?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme#32]
How do I set "$maxCount" on the stream?

I tried "my_stream/metadata", with `WriteEvents` but it just creates a new stream: `my_stream/metadata`.

However, when I issue this command from bash, it works:

```
curl -i "http://127.0.0.1:2113/streams/my_stream/metadata" -H "Content-Type:application/vnd.eve    ntstore.events+json" -d '[
     {
         "eventId":"5f6380f5-c885-46e6-8abb-781a0c8b462e",
         "eventType" : "set_snapshot_count",
         "data" : {
             "$maxCount" : 1,
         },
     }
   ]'
```

**Comment by drozzy** [comment]
Here is what I tried:

```
set_snapshot_metadata(StreamId, _) ->
     Data = #{              
     │   '$maxCount' => ?NUM_SNAPSHOTS_TO_KEEP
     },
     EventType = set_max_count,   
     MetadataStreamId = <<StreamId/binary, "/metadata">>,
     myevstore:append_events(MetadataStreamId, [{EventType, Data}], -2).
```

where `append_events` just json encodes the data, and calls `Elixir.Extreme.Messages.WriteEvents`.

Strangely, I just get an empty `metadata` stream, with _nothing_ in it :(

**Comment by drozzy** [comment]
I'm stuck :-) Nothing seems to be doing it.

Basically, I can't reproduce the curl command I gave in the beginning.

**Comment by burmajam** [comment]
Hi drozzy. We didn't implement that one. You can either send PR or simply call ES using httpoison

**Comment by drozzy** [comment]
Thanks, good idea, I'll just call http endpoint!

Sorry, I'm not elixir hacker.
