### ISSUE TITLE
What is DB?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme#33]
Sorry for the dumb question, but what is `DB` in the code examples?
E.g.:
`DB.ack_event(MyListener, stream_name, event_number)`

Is this part of elixir? I'm still learning it.

**Comment by burmajam** [comment]
https://github.com/exponentially/extreme/blob/master/test/listener_test.exs#L9 DB is wrapper module around some persistence. For testing purposes we are using [Agent](http://elixir-lang.org/getting-started/mix-otp/agent.html) but in production you can use whatever suites you the best (dets, Postgrex, ...)

**Comment by drozzy** [comment]
Right, got it.

Thanks.
