### ISSUE TITLE
Documented data_content_type

### ISSUE THREAD

**Issue by tudborg** [exponentially/extreme#4]
Messages could need enum or at least documentation for data_content_type.
(I'll make a PR soon)

See https://github.com/EventStore/EventStore/issues/805

**Comment by burmajam** [comment]
Hi tbug,

I do agree that documentation should be better for protobuf messages, but I'd rather link to EventStore documentation itself since Extreme.execute function just proxies protobuf messages to/from EventStore. We are opened for improvements, so I'm looking forward to take a look at PR.

**Comment by mjaric** [comment]
Hi tbug,

Did you had chance to work on PR?

**Comment by tudborg** [comment]
Not yet.
I'm doing it as part of a larger project and I'm not 100% sure of what I want to do yet.
I'm in the middle of reading Extreme source. When I have a better understanding of what is going on, I'll
try and do some draft docs, and possibly some code (I'll do separate PR's for docs and code :+1: )
Will probably be during this week, but no promises.

**Comment by tudborg** [comment]
We made a decision to switch to the HTTP API instead of using Extreme.
I won't get the time to add to Extreme.

**Comment by mjaric** [comment]
Hi tbug,

Could you please at least tell us what is missing in this library which make you decide switching to HTTP api?

Thank you

**Comment by tudborg** [comment]
Yes, ofc.
We need competing consumers, and don't need the added throughput of the TCP protocol. As the TCP protocol is terribly documented we figured it would be a pain to continue using it.
The HTTP API is way better documented, so writing a thin wrapper around the bits we need should be trivial.
