### ISSUE TITLE
Release deadlock fix

### ISSUE THREAD

**Issue by tonyvanriet** [exponentially/extreme#49]
Are you planning to do another hex release any time soon to include the deadlock fix?
Looks like the most recent hex release, 0.10.3, was just a few days before the #47 PR was merged.

If you're not ready to do that release yet, or you would like to vet that fix in other environments, I'd be happy to take the git dependency instead and release that into the environment where we first encountered the deadlock.

Thanks.

**Comment by burmajam** [comment]
Hi @tonyvanriet, I forgot to publish it to hex. Thanks for reminding. I just did it. You can find it as 0.10.4 version on hex

Best
