### ISSUE TITLE
Compatibility with Elixir 1.6.x

### ISSUE THREAD

**Issue by azuken** [exponentially/extreme#53]
Hi,

Me and my team have upgraded our Elixir project to new version (1.6.3). After some tests, we do not see any problems with our application, but we have a warning which says that extreme requires Elixir 1.3, or 1.4, or 1.5.

Can you tell me if a new release is coming, and if not, why ?
If there is a serious compatibility issue, we want to know, to see if we can deploy it into production or not.

Thanks in advance

**Comment by burmajam** [comment]
Hi @azuken,

There are no compatibility issues whatsoever. We had pull request for some bug #50 but that brought back some previously solved bug. That's the reason why we are not pushing new version still. I think that I will revert that pull request and bump elixir version so new patch release can be published to hex.

If you are in rush I can do my best to do it today.

Best

**Comment by azuken** [comment]
Thanks for your response,

Actually we're not really in rush, but it will be great if it will be published before our next release, expected in 3 weeks.

Best regards

**Comment by burmajam** [comment]
That's great. I expect that we will solve both problems by then. Regarding this warning, I know it makes noise but you are totally safe. We are seeing this as well but everything works as expected.

Please stay tuned for new version.
