### ISSUE TITLE
httpoison dependency still locked to 0.11 instead of 1.X.X

### ISSUE THREAD

**Issue by azuken** [exponentially/extreme#58]
Hello,

I was updating my project dependencies, and I saw that extreme is still asking for 0.11 httpoison version, while 1.0.0 version was released since january, and the latest in june (1.2.0).

Why do you not upgrade this dependency ? Technical constraint ?

Thank you in advance for your response.

**Comment by burmajam** [comment]
Hi Alexandre. To be honest I wasn’t aware of that. Httpoison is used only
for gossip with ES cluster. I’ll look into this next week but please feel
free to send PR if you’d like in the meantime

**Comment by azuken** [comment]
Ok no problem ! I will open a PR as soon as possible.

Thanks

**Comment by azuken** [comment]
It seems I can't push my branch on the repo. Is there anything to do first ? (It's my first contribution on an open source project)

**Comment by mjaric** [comment]
Hi @azuken Thank you for contribution. The way thing work here are that You need to fork this repo first, then clone your fork locally on your computer, change code, commit and push to your fork and finally make pull request from your fork. You will see green button on yours fork page. 

Here is detailed explanation https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by azuken** [comment]
Thank you for your explanation !

**Comment by burmajam** [comment]
Bumped version to 0.13.1 and published to hex. Thanks for contribution @azuken.
