### ISSUE TITLE
CommitTimeout?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme#61]
When using extreme_system sometimes I get this:

```
 Error saving events {:error, {:error, :CommitTimeout, %Extreme.Msg.WriteEventsCompleted{commit_position: 0, current_version: -1, first_event_number: -2147483648, last_event_number: -2147483648, message: "Commit phase timeout.", prepare_position: -2147483648, result: :CommitTimeout}}}
```

Do you know why this is happening?

**Comment by burmajam** [comment]
It happened to me few times and as far as I saw in grafana it was GC time. We didn't experience this issue in prod however. So I guess "let it crash" :)

**Comment by drozzy** [comment]
Funny, the only place I experience it is in production. When I send two commands to my aggregate in a sequence with extreme_system.

**Comment by mjaric** [comment]
@drozzy The error you are getting is  Eventstore server response, it fails to commit append to stream within expected time. 

If that happens rarely, say during low load, I would first check if eventstore server HDD goes to sleep, turn off power saver options for drive that is used by eventstore service. 

If that does not work for you, then try to get _**max**_ stat from your app about how long it takes extreme to append single batch to event store, if you see values close to 2 seconds, then you need quicker HDDs on that server. Last resort is to increase Eventatore server commit timeout value during server startup, either using environment variable `COMMIT_TIMEOUT_MS` or `--commit-timeout-ms` flag, but I'm not sure if that will solve your problem! 

You can allways file an issue to eventstore git repo and ask for help if you don't have paid support/license for eventstore. They are very prompt even for OSS users.

**Comment by drozzy** [comment]
It's so odd because I'm literally sending like 1 command per second. I'm on DO volume.

Ok, thanks for help.
