### ISSUE TITLE
Which version should I use?

### ISSUE THREAD

**Issue by ryanwinchester** [exponentially/extreme#66]
Can I use branch 1.0.0?

Does it work and should I expect it to break?

**Comment by burmajam** [comment]
Hi @ryanwinchester. branch 1.0.0 is maintained and should be used. It is used in production for more than a year now and works better than hex version (v0.xxx). The only thing it is missing from v0 is persistent subscriptions (and more documentation)

**Comment by ryanwinchester** [comment]
Thanks. Is there any plan to release on Hex?

**Comment by burmajam** [comment]
docs must be improved and preferably persistent subscriptions implemented
