### ISSUE TITLE
read-only client modules

### ISSUE THREAD

**Issue by the-mikedavis** [exponentially/extreme#69]
Similar to the [Ecto option for read-only repositories](https://hexdocs.pm/ecto/Ecto.Repo.html#module-read-only-repositories), it would be useful to be able to configure an extreme client module as read-only.

I'm imagining that this parameter gets passed in to the config the same way one passes in `db_type` or `hostname` (just a `read_only: true` that defaults to `false`)

Read-only extreme client modules should support executing these message types:

- `ReadEvent`
- `ReadStreamEvents`
- `ReadStreamEventsBackward`
- `ReadAllEvents`
- `ConnectToPersistentSubscription`
- `SubscribeToStream`

This could help increase write-safety for read models. We occasionally connect local development read model services to production eventstores for the sake of projecting real prod data, and having some extra guarantees around writing would make that less scary.

Am I missing any key message types? Would this need any special considerations for clustered eventstores (e.g. auto-select read mode instead of master mode)? I'd be happy to PR for this 👍

**Comment by burmajam** [comment]
Hey Michael. That is neat idea. Pattern match `RequestManager.handle_call({:execute, correlation_id, message}, from, %State{} = state)` function on type of `message` struct sounds like a way to do that, but that setting should be put in a state in its `init` function as well.

I don't know about additional persistent subscription related messages if they are needed (like PersistentSubscriptionAckEvents). I just saw your last PR, so I'll take a look there as well.

So yes, please feel free to make PR for this and when persistent subscriptions are done and docs/tests are improved I think we could push v1 to hex finally :)
